### ISSUE TITLE
Failed to get a stored value in modified webrtc-browser-e2e example. 

### ISSUE THREAD

**Issue by zanetu** [omphalos/kad-webrtc#5] opened 2015-12-26 19:17 UTC
1. Preamble
Since I am new to kde-webrtc, please let me know if I have used it in a wrong way. 

2. Synopsis
a. Set up 3 nodes, namely, node1, node2 and node3. 
b. Connect node2 to node1. Use node2 to `put` a value upon connection. 
c. After `put` is complete, Connect node3 to node1. Use node3 to `get` the stored value upon connection. 

3. Result (after `examples/webrtc-browser-e2e/index.html` is open for about 45sec)
Expected: "boop"
Actual: "undefined"

4. Code (`examples/webrtc-browser-e2e/index.js`)

```
'use strict';

var kademlia = require('kad');
var KadLocalStorage = require('kad-localstorage');
var WebRTC = require('../..');
var webSocket = require('./web-socket');
var SignalClient = require('./signal-client');
var EventEmitter = require('events').EventEmitter;
var signalClient1 = new SignalClient('node1');
var signalClient2 = new SignalClient('node2');
var signalClient3 = new SignalClient('node3');

webSocket.on('open', function() {

  // Create our first node
  var node1 = new kademlia.Node({
    transport: new WebRTC({ nick: 'node1' }, { signaller: signalClient1 }),
    storage: new KadLocalStorage('node1')
  });

  // Create a second node
  var node2 = new kademlia.Node({
    transport: new WebRTC({ nick: 'node2' }, { signaller: signalClient2 }),
    storage: new KadLocalStorage('node2')
  });

  // Create a third node
  var node3 = new kademlia.Node({
    transport: new WebRTC({ nick: 'node3' }, { signaller: signalClient3 }),
    storage: new KadLocalStorage('node3')
  });

  node2.on('connect', onConnect2);
  node2.connect({ nick: 'node1' });

  function onConnect2() {
    node2.put('beep', 'boop', onPut);
  }

  function onPut(err) {
    node3.on('connect', onConnect3);
    node3.connect({ nick: 'node1' });
  }

  function onConnect3() {
    node3.get('beep', onGet);
  }

  function onGet(err, value) {
    alert(value); // 'undefined' instead of 'boop'
  }

});
```

**Comment by gordonwritescode** [comment] 2015-12-26 22:44
This sounds like an issue with the kad-localstorage dependency. This package depends on 0.0.5, but the kad version it uses required 0.0.7. 

Since kad-localstorage ships with kad now, try importing with:

```js
var KadLocalStorage = kademlia.storage.LocalStorage;
```

@omphalos we can probably remove the kad-localstorage dependency from here to ensure that everyone gets the version that is referenced by kad?

**Comment by gordonwritescode** [comment] 2015-12-26 22:48
Also sorry for the API changes/disruption. If you need a "stable" version of kad, you can use 0.9.x until we remove the beta tag, then upgrade. I'm trying to keep the necessary changes for upgrade from 0.9.x to 1.x.x straightforward and will include an upgrade guide in the main repo soon.

**Comment by omphalos** [comment] 2015-12-26 22:55
@gordonwritescode I agree I need to fix the `kad-localstorage` dependency.  I'll do that.  It does look like there is something else going on here, besides the issue with `kad-localstorage`:

```js
'use strict';

var kademlia = require('kad');
var WebRTC = require('../..');
var webSocket = require('./web-socket');
var SignalClient = require('./signal-client');
var EventEmitter = require('events').EventEmitter;
var signalClient1 = new SignalClient('node1');
var signalClient2 = new SignalClient('node2');
var signalClient3 = new SignalClient('node3');

webSocket.on('open', function() {

  // Create our first node
  var node1 = new kademlia.Node({
    transport: new WebRTC({ nick: 'node1' }, { signaller: signalClient1 }),
    storage: new kademlia.storage.LocalStorage('node1')
  });

  // Create a second node
  var node2 = new kademlia.Node({
    transport: new WebRTC({ nick: 'node2' }, { signaller: signalClient2 }),
    storage: new kademlia.storage.LocalStorage('node2')
  });

  // Create a third node
  var node3 = new kademlia.Node({
    transport: new WebRTC({ nick: 'node3' }, { signaller: signalClient3 }),
    storage: new kademlia.storage.LocalStorage('node3')
  });

  node2.on('connect', onConnect2);
  node2.connect({ nick: 'node1' });

  function onConnect2() {
    node2.put('beep', 'boop', onPut);
  }

  function onPut(err) {
    node3.on('connect', onConnect3);
    node3.connect({ nick: 'node1' });
  }

  function onConnect3() {
    node3.get('beep', onGet);
  }

  function onGet(err, value) {
    alert(value); // 'undefined' instead of 'boop'
  }

});
```

I get the same behavior here.

I want to try to repro with the TCP transport to see if the issue is in `kad` or `kad-webrtc`.

**Comment by omphalos** [comment] 2015-12-27 00:58
This looks like an issue with kad-webrtc.  I'll keep looking.

**Comment by omphalos** [comment] 2015-12-27 02:43
@zanetu There was a bug in the example signaling code that broke when more than two nodes were added.  That's fixed now.  Thanks for bringing this up, and I'm sorry you've had to deal with these two problems.  If you run into any other problems, please let me know.

**Comment by omphalos** [comment] 2015-12-27 02:46
@gordonwritescode I've updated `kad-webrtc`'s use of `localStorage`.  Thanks for pointing that out - I didn't realize it was an issue.

BTW I think the new storage module is pretty nice.

**Closed by omphalos** 2015-12-27 02:46 UTC

**Comment by zanetu** [comment] 2015-12-27 03:18
[**@omphalos**](https://github.com/omphalos) commented on [Dec 26, 2015, 9:43 PM EST](https://github.com/omphalos/kad-webrtc/issues/5#issuecomment-167376004 "2015-12-27T02:43:02Z - Replied by Github Comment Enhancer"):
> [@zanetu](https://github.com/zanetu) There was a bug in the example signaling code that broke when more than two nodes were added.  That's fixed now.  Thanks for bringing this up, and I'm sorry you've had to deal with these two problems.  If you run into any other problems, please let me know.

Fix verified. Thanks.
